services:
  - type: web
    name: rapid-crew-backend
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:application
    autoDeploy: true
